version: '3'

services:
  # mongo_express_sh:
  #   container_name: mongo_express_sh
  #   image: mongo-express
  #   depends_on:
  #     - mongo
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=mongo
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo_humongous
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo_1234
  #     - ME_CONFIG_BASICAUTH_USERNAME=admin
  #     - ME_CONFIG_BASICAUTH_PASSWORD=tribes
  #   ports:
  #     - '8081:8081'
  #   volumes: 
  #     - ./data:/data/db      
  #   networks:
  #     - mongo-compose-network

  mongo_sh_1:
    image: mongo:6.0.1
    container_name: sdsw_mongo_sh_1_database
    ports:
      - 27014:27017
    volumes:
      - mongo_sh_data1:/data/db
      # - ./src:/app/src
      # - ./scripts/rs_init.sh:/scripts/rs-init.sh
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: mongo_humongous
    #   MONGO_INITDB_ROOT_PASSWORD: mongo_1234
    networks:
      - mongo_sh_compose_network
    command: mongod --replSet mongo_sh_rs_1 --shardsvr --port 27017

  mongo_sh_2:
    image: mongo:6.0.1
    container_name: sdsw_mongo_sh_2_database
    ports:
      - 27015:27017
    volumes:
      - mongo_sh_data2:/data/db
    networks:
      - mongo_sh_compose_network
    command: mongod --replSet mongo_sh_rs_2 --shardsvr --port 27017

  mongo_sh_rs_config:
    image: mongo:6.0.1
    container_name: sdsw_mongo_sh_rs_config_database
    ports:
      - 27016:27017
    volumes:
      - mongo_sh_rs_config_data:/data/db
    networks:
      - mongo_sh_compose_network
    command: mongod --port 27017 --configsvr --replSet configSet

  mongos_sh_configdb:
    image: mongo:6.0.1
    container_name: sdsw_mongos_sh_configdb_database
    ports:
      - 27020:27017
    volumes:
      - mongos_sh_configdb_data:/data/db
      - ./src:/app/src
    depends_on:
      - mongo_sh_rs_config
    networks:
      - mongo_sh_compose_network
    command: mongos --port 27017 --configdb configSet/mongo_sh_rs_config:27017

volumes:
  mongo_sh_data1:
  mongo_sh_data2:
  mongo_sh_rs_config_data:
  mongos_sh_configdb_data:

networks: 
    mongo_sh_compose_network:
      driver: bridge