version: '3'

services:
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo_humongous
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo_1234
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=tribes
    ports:
      - '8081:8081'
    volumes: 
      - ./data:/data/db      
    networks:
      - mongo-compose-network

  mongo:
    image: mongo:6.0.1
    container_name: sdsw_mongo_database
    ports:
      - 27018:27017
    volumes:
      - mongodata:/data/db
      - ./src:/app/src
    environment:
      # MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: mongo_humongous
      MONGO_INITDB_ROOT_PASSWORD: mongo_1234
    networks:
      - mongo-compose-network

volumes:
  mongodata:

networks: 
    mongo-compose-network:
      driver: bridge